# Generated by Django 5.2.1 on 2025-05-21 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('budget', models.CharField(max_length=100)),
                ('possesseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiels_possedes', to='gestion_materiel.enseignant')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiels_responsable', to='gestion_materiel.enseignant')),
                ('salle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_materiel.salle')),
            ],
        ),
        migrations.CreateModel(
            name='Accessoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('etat', models.CharField(max_length=100)),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessoires', to='gestion_materiel.materiel')),
            ],
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_passation', models.DateTimeField(auto_now_add=True)),
                ('occasion', models.CharField(max_length=100)),
                ('objectif', models.TextField()),
                ('ancien_possesseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprunts_anciens', to='gestion_materiel.enseignant')),
                ('nouveau_possesseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprunts_nouveaux', to='gestion_materiel.enseignant')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_materiel.materiel')),
                ('lieu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_materiel.salle')),
            ],
        ),
    ]
