# Generated by Django 5.2.1 on 2025-05-21 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_materiel', '0002_emprunt_accessoires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessoire',
            name='etat',
        ),
        migrations.RemoveField(
            model_name='accessoire',
            name='materiel',
        ),
        migrations.RemoveField(
            model_name='emprunt',
            name='accessoires',
        ),
        migrations.AddField(
            model_name='materiel',
            name='accessoire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_materiel.accessoire'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='etat',
            field=models.CharField(choices=[('Neuf', 'Neuf'), ('Bon état', 'Bon état'), ('Usé', 'Usé'), ('HS', 'Hors Service')], default='Neuf', max_length=100),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='budget',
            field=models.CharField(choices=[('annee_courante', 'Année Courante'), ('projets', 'Projets'), ('financements_exceptionnels', 'Financements Exceptionnels')], max_length=100),
        ),
    ]
