# Generated by Django 5.2.1 on 2025-05-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_materiel', '0003_remove_accessoire_etat_remove_accessoire_materiel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprunt',
            old_name='date_passation',
            new_name='date_emprunt',
        ),
        migrations.AlterField(
            model_name='materiel',
            name='budget',
            field=models.CharField(choices=[('Année Courante', 'Année Courante'), ('Projets', 'Projets'), ('Financements Exceptionnels', 'Financements Exceptionnels')], max_length=100),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='type',
            field=models.CharField(choices=[('Smartphone', 'Smartphone'), ('Tablette', 'Tablette'), ('Ordinateur', 'Ordinateur'), ('Imprimante', 'Imprimante'), ('Projecteur', 'Projecteur'), ('Pointeur Laser', 'Pointeur Laser'), ('Écran', 'Écran'), ('Autre', 'Autre')], max_length=50),
        ),
    ]
